#!/bin/bash

# 使用 --multi 参数支持多选
selected_paths=$(ali ls | fzf --multi)

if [ -n "$selected_paths" ]; then
  # 遍历每一行的选择并处理
  echo "$selected_paths" | while read -r selected_path; do
    # 提取文件路径
    target_item=$(echo "$selected_path" | awk '{for(i=5;i<=NF;i++) printf $i (i==NF?"\n":" ");}' | sed 's/\/$//')
    echo "Downloading: $target_item"
    ali d "$target_item"
  done
else
  echo "No selection made."
fi
